export { default as IconCategoryAnimal } from './CategoryAnimal';
export { default as IconCategoryBusiness } from './CategoryBusiness';
export { default as IconCategoryFolks } from './CategoryFolks';
export { default as IconCategoryGift } from './CategoryGift';
export { default as IconCategoryHealth } from './CategoryHealth';
export { default as IconCategoryHousing } from './CategoryHousing';
export { default as IconCategoryNature } from './CategoryNature';
export { default as IconCategoryNutrition } from './CategoryNutrition';
export { default as IconCategoryPray } from './CategoryPray';
export { default as IconCategoryPromise } from './CategoryPromise';
export { default as IconCategoryRest } from './CategoryRest';
export { default as IconCategoryScience } from './CategoryScience';
export { default as IconCategorySport } from './CategorySport';
export * from './helpers';
export * from './types';
export * from './ui';
