export enum Category {
  Animal = 'Animal',
  Business = 'Business',
  Folks = 'Folks',
  Gift = 'Gift',
  Health = 'Health',
  Housing = 'Housing',
  Nature = 'Nature',
  Nutrition = 'Nutrition',
  Pray = 'Pray',
  Promise = 'Promise',
  Rest = 'Rest',
  Science = 'Science',
  Sport = 'Sport',
}
